#pragma once
// paragon-champions: Epic's Paragon heroes as playable champions (Docs/ParagonChampions.md).
//
// The Paragon packs (Content/Paragon*) are Epic-licensed and LOCAL ONLY: never committed. Everything this module
// commits is code plus Content/Data/ParagonChampions.json, which only references /Game/Paragon* paths. A hero is
// registered only when its pack is installed locally (and -CireNoParagon is absent), so a clean clone plays exactly
// as before.
//
// Content/Data/ParagonChampions.json (generated by Tools/AuthorParagonChampions.py from Tools/InspectParagon.py's
// inventory) carries:
//   roster      a CireChampionRoster document (same schema/validation as ChampionRoster.json), appended to the roster
//   abilities / champions / schools   an Ability DB overlay (same schema as Abilities.json), merged into the DB;
//               "pool" abilities also join every matching-role champion's Skill Shop pool
//   recipes     the delivery recipe of every Paragon ability (this module; numbers stay in the Ability DB)
//   bindings    ChampionArtBindings-style monster_native rows: the hero's own mesh + Paragon clips per ability
//   heroes      presentation (pack, skins, anim blueprint, voice cues, portrait) and the inventory summary
//   creeps      ParagonMinions inventory (candidates for monster variants; not used by gameplay yet)
#include "CoreMinimal.h"

class AActor;
class ACireHero;
class ACireGameMode;
class UTexture2D;
class USoundBase;
class UWorld;
struct FCireHitShape;
struct FCireChampionProfile;
struct FCireAbilityDef;
struct FCireChampionKit;
enum class ECireSpellCue : uint8;

namespace CireParagonChampions
{
    /** Content/Data/ParagonChampions.json */
    CIRESTEAMSURVIVAL_API FString DataPath();
    /** True when at least one Paragon hero pack is installed and -CireNoParagon is absent. */
    CIRESTEAMSURVIVAL_API bool IsEnabled();
    /** Paragon profile ids registered this session (installed packs only), data order. */
    CIRESTEAMSURVIVAL_API const TArray<FString>& HeroIds();
    CIRESTEAMSURVIVAL_API bool IsParagon(const FString& ProfileId);
    /** Every Paragon hero authored in the data (installed or not). */
    CIRESTEAMSURVIVAL_API int32 AuthoredCount();

    // ---- registration hooks (additive; called by CireChampionRoster::Reload / CireAbilityDB::Reload) ----
    /** Appends the installed Paragon heroes whose ids are not already in the roster. */
    CIRESTEAMSURVIVAL_API void AppendProfiles(TArray<FCireChampionProfile>& InOut);
    /** Adds the Paragon abilities and kits to the DB; pool abilities join the matching-role kits' purchasable lists. */
    CIRESTEAMSURVIVAL_API void MergeAbilities(TArray<FCireAbilityDef>& Abilities, TMap<FString, FCireChampionKit>& Kits);

    // ---- skills (routed from CireSignatureSkills, the same contract as CireKitSkills) ----
    CIRESTEAMSURVIVAL_API bool Knows(const FString& Id);
    CIRESTEAMSURVIVAL_API bool Handles(const FString& Id);
    CIRESTEAMSURVIVAL_API bool IsPassive(const FString& Id);
    CIRESTEAMSURVIVAL_API const TArray<FString>& AllIds();
    CIRESTEAMSURVIVAL_API bool Cast(ACireHero* Hero, int32 Slot, const FString& Id);
    CIRESTEAMSURVIVAL_API bool DescribeShape(const FString& Id, FCireHitShape& Out);
    /** Guard / empower buffs and the damage passives. */
    CIRESTEAMSURVIVAL_API float ModifyOutgoingDamage(AActor* Source, AActor* Target, float Amount, const FString& AbilityName);
    /** Lifesteal passives. */
    CIRESTEAMSURVIVAL_API void OnAbilityHit(AActor* Source, AActor* Target, const FString& AbilityName, float Applied);
    CIRESTEAMSURVIVAL_API float MoveSpeedMultiplier(const ACireHero* Hero);
    CIRESTEAMSURVIVAL_API float AttackSpeedBonus(const ACireHero* Hero);
    /** Buff record ids (BuffVisuals.json rows exist for each). */
    CIRESTEAMSURVIVAL_API const TArray<FName>& BuffIds();

    // ---- presentation (local) ----
    /** The hero's own Paragon particle systems for a cue of one of its abilities (Cascade or Niagara). Returns systems spawned. */
    CIRESTEAMSURVIVAL_API int32 PlayFX(UWorld* World, FName SkillId, FVector From, FVector To, ECireSpellCue Cue, float Scale);
    /** Draft portrait captured locally from the hero mesh (/Game/ParagonDerived/Portraits/T_Portrait_<id>), or null. */
    CIRESTEAMSURVIVAL_API UTexture2D* Portrait(const FString& ProfileId);
    /** Voice cue of the hero ("select", "lock", "cast"), or null. */
    CIRESTEAMSURVIVAL_API USoundBase* Voice(const FString& ProfileId, const FString& Key);
    /** Champion-select painting id (an existing T_DraftBg_<id>) for a Paragon hero, empty otherwise. */
    CIRESTEAMSURVIVAL_API FString DraftBackground(const FString& ProfileId);
    /** Ability ids of a hero's own Paragon kit (RMB, Q, E, then the ultimate). */

    CIRESTEAMSURVIVAL_API TArray<FString> OwnAbilities(const FString& ProfileId);

#if !UE_BUILD_SHIPPING
    /** Native checks: data, registration, DB merge, art binding + clips, every delivery casts. Logs CIRE_PARAGON_SMOKE_PASS/FAIL. */
    CIRESTEAMSURVIVAL_API bool RunSmoke(ACireGameMode* Mode);
    /** -CireParagonGallery: one turntable capture per hero (Saved/ParagonGallery/<stamp>/<id>_*.png). */
    CIRESTEAMSURVIVAL_API bool TickGallery(ACireGameMode* Mode, float DeltaSeconds);
#endif
}
