#pragma once
// monster-races: monster races, rank colours, per-match skill draws and wave-gated skill unlocks.
// Data: Content/Data/Races.json (generated by Tools/AuthorRaces.py), Waves.json "skillProgression" and
// "campaign", and the optional art overlay Content/Data/RaceMeshes.tripo.json. See Docs/Races.md.
#include "CoreMinimal.h"
#include "CireNPCArchetypes.h"

class ACireGameMode;
class ACireMonster;
class ACireHero;
class UWorld;
class USkeletalMeshComponent;

/** WoW-style quality tiers: colour signifies rank and strength. Values are replicated as uint8. */
enum class ECireNPCRank : uint8 { Normal, Veteran, Elite, Champion, Warlord, Mythic, Count };

struct CIRESTEAMSURVIVAL_API FCireRankStyle
{
    FString Label = TEXT("Normal");
    FLinearColor Color = FLinearColor(.82f, .8f, .74f), Trim = FLinearColor::Transparent;
    float Health = 1.f, Damage = 1.f, Size = 1.f;
    int32 SkillBonus = 0;
    /** Skin strengths: armour recolour, whole-body tint, emissive trim glow, fresnel rim. */
    float ArmorTint = 0.f, BodyTint = 0.f, Glow = 0.f, Rim = 0.f;
    ECireNPCClass Classification = ECireNPCClass::Normal;
};

struct CIRESTEAMSURVIVAL_API FCireRacePalette
{
    FString Name;
    FLinearColor Base = FLinearColor::White, Accent = FLinearColor::White;
};

struct CIRESTEAMSURVIVAL_API FCireRace
{
    FName Id;
    FString Name, Short, Lore, OriginNote;
    TArray<FString> PlayerRaces, Profiles;
    FLinearColor Base = FLinearColor::White, Accent = FLinearColor::White, Secondary = FLinearColor::White, Glow = FLinearColor::White;
    TArray<FCireRacePalette> Variants;
    FName Footsteps, AmbienceCue, VoiceCue;
    /** line|bruiser|tank|caster|ranged|special -> unit id; warlord|colossus -> boss id. */
    TMap<FName, FName> Slots, Bosses;
    TArray<FName> Units; // the six units then the two bosses
    FCireRacePalette Palette(int32 Index) const;
};

struct CIRESTEAMSURVIVAL_API FCireRaceDatabase
{
    bool bValid = false;
    TArray<FName> Order;
    TMap<FName, FCireRace> Races;
    FCireRankStyle Ranks[static_cast<int32>(ECireNPCRank::Count)];
};

/** Waves.json "skillProgression": when monsters get skills and how strong they are. */
struct CIRESTEAMSURVIVAL_API FCireSkillProgression
{
    /** Global wave number of the first wave with monster skills (waves before it: basic attacks only). */
    int32 FirstSkillWave = 4;
    /** +1 skill every N waves after the first skill wave. */
    int32 UnlockEveryWaves = 3;
    /** Skills a normal unit can reach (ranks add their skill bonus on top). */
    int32 MaxSkills = 3;
    /** Skill tier (I..MaxTier) rises every N waves after the first skill wave. */
    int32 TierEveryWaves = 5;
    int32 MaxTier = 3;
    /** Per tier above I. */
    float TierDamage = .2f, TierCooldown = .1f, TierDuration = .15f;
    bool operator==(const FCireSkillProgression& O) const;
};

/** Waves.json "campaign": which race each cycle fields, boss alternation and rank promotions. */
struct CIRESTEAMSURVIVAL_API FCireCampaign
{
    /** Race per cycle (wraps). An entry may mix races with '+' ("hollow+blightwood"): rows alternate between them. */
    TArray<FString> RaceRotation;
    /** Palette variant per cycle wrap: the second lap of the rotation reskins with variant 1, and so on. */
    bool bReskinOnWrap = true;
    /** From these cycles (1-based), every Nth normal wave unit is promoted. 0 disables a tier. */
    int32 VeteranFromCycle = 2, EliteFromCycle = 3, ChampionFromCycle = 4, MythicBossFromCycle = 3;
    int32 PromoteEvery = 4;
    bool operator==(const FCireCampaign& O) const;
};

/** Soak/diagnostic counters since process start (server). */
struct CIRESTEAMSURVIVAL_API FCireRaceStats
{
    int32 Casts = 0, RiderHits = 0, Summoned = 0;
    int32 EarliestCastWave = 0; // global wave of the first non-basic monster skill (0 = none yet)
    FString Races;              // races whose units were configured, in order of appearance
};

struct CIRESTEAMSURVIVAL_API FCireSkillPlan
{
    int32 Count = 0; // skills allowed (before the pool cap)
    int32 Tier = 0;  // 0 = no skills, 1..MaxTier
};

namespace CireRaces
{
    // ---- data ----
    /** Loads Races.json into the NPC archetype database (called by CireNPCArchetypes::Reload). */
    CIRESTEAMSURVIVAL_API bool MergeInto(FCireNPCDatabase& Database, FString& Error);
    CIRESTEAMSURVIVAL_API const FCireRaceDatabase& Get();
    CIRESTEAMSURVIVAL_API const FCireRace* FindRace(FName RaceId);
    /** Race of an archetype (NAME_None for units outside every race). */
    CIRESTEAMSURVIVAL_API FName RaceOf(FName ArchetypeId);
    /** Unit of a race by slot; "boss" alternates warlord/colossus by cycle (0-based: even cycles colossus). */
    CIRESTEAMSURVIVAL_API FName UnitFor(FName RaceId, FName Slot, int32 Cycle = 0);
    /** The slot an archetype fills in its race (line, bruiser, ..., warlord, colossus). */
    CIRESTEAMSURVIVAL_API FName SlotOf(FName ArchetypeId);
    CIRESTEAMSURVIVAL_API const TArray<FName>& SlotNames();

    // ---- ranks ----
    CIRESTEAMSURVIVAL_API const FCireRankStyle& Rank(ECireNPCRank Rank);
    CIRESTEAMSURVIVAL_API const TCHAR* RankId(ECireNPCRank Rank);
    CIRESTEAMSURVIVAL_API bool ParseRank(const FString& Text, ECireNPCRank& Out);
    CIRESTEAMSURVIVAL_API ECireNPCRank RankFromClass(ECireNPCClass Class);
    CIRESTEAMSURVIVAL_API ECireNPCRank RankOf(const ACireMonster* Monster);
    CIRESTEAMSURVIVAL_API FLinearColor RankColor(const ACireMonster* Monster);

    // ---- skills ----
    /** Wave/rank schedule: how many skills and which tier at a global wave number. */
    CIRESTEAMSURVIVAL_API FCireSkillPlan Plan(const FCireSkillProgression& Rules, int32 GlobalWave, ECireNPCRank Rank);
    /** Pool skills (non-basic, non-core) of an archetype in this match's seeded order. */
    CIRESTEAMSURVIVAL_API TArray<FName> MatchOrder(int32 Seed, const FCireNPCArchetype& Archetype);
    /** Active skills (ids) for a unit: core skills plus the first N of the match order (normal ranks stay inside poolDraw). */
    CIRESTEAMSURVIVAL_API TArray<FName> Loadout(int32 Seed, const FCireNPCArchetype& Archetype, ECireNPCRank Rank, int32 Count);
    CIRESTEAMSURVIVAL_API FString TierSuffix(int32 Tier);

    // ---- match runtime (server) ----
    /** Chooses this match's skill seed (-CireRaceSeed=N fixes it) and publishes it on the game state. */
    CIRESTEAMSURVIVAL_API void BeginMatch(ACireGameMode* Mode, int32 Seed = -1);
    CIRESTEAMSURVIVAL_API int32 MatchSeed(const UWorld* World);
    /** Applies rank (stats, classification, size, colours) and palette to a configured monster. */
    CIRESTEAMSURVIVAL_API void ApplyRank(ACireMonster* Monster, ECireNPCRank Rank, int32 Palette = 0);
    /** Draws and applies the skill loadout. Count/Tier < 0 = schedule; 0 = none. */
    CIRESTEAMSURVIVAL_API void ApplyLoadout(ACireMonster* Monster, const FCireSkillProgression& Rules, int32 GlobalWave, int32 CountOverride = -1, int32 TierOverride = -1);
    /** Challenge-pack units: elite (tier 1-2) or champion (tier 3+), leaders warlord; skills on the wave schedule. */
    CIRESTEAMSURVIVAL_API void ApplyPackUnit(ACireMonster* Monster, int32 Tier, bool bLeader, int32 GlobalWave);

    // ---- combat hooks (server) ----
    CIRESTEAMSURVIVAL_API bool IsAbilityActive(const ACireMonster* Monster, FName AbilityId);
    CIRESTEAMSURVIVAL_API float TierDamage(const ACireMonster* Monster);
    CIRESTEAMSURVIVAL_API float TierCooldown(const ACireMonster* Monster);
    CIRESTEAMSURVIVAL_API float TierDuration(const ACireMonster* Monster);
    /** Size multiplier of the monster's rank. */
    CIRESTEAMSURVIVAL_API float RankSize(const ACireMonster* Monster);
    /** Pull and summon starts; false when the ability cannot be used now. */
    CIRESTEAMSURVIVAL_API bool CanSummon(const ACireMonster* Monster, const FCireNPCAbility& Ability);
    /** Riders, pulls and summons when a cast completes. Returns the champions affected. */
    CIRESTEAMSURVIVAL_API int32 OnAbilityReleased(ACireMonster* Monster, const FCireNPCAbility& Ability, FVector Aim);
    CIRESTEAMSURVIVAL_API int32 SpawnSummons(ACireMonster* Monster, const FCireNPCAbility& Ability);
    /** Champions currently rooted / silenced by monster skills (buff records; valid on clients). */
    CIRESTEAMSURVIVAL_API bool IsRooted(const ACireHero* Hero);
    CIRESTEAMSURVIVAL_API FCireRaceStats Stats();
    CIRESTEAMSURVIVAL_API bool IsSilenced(const ACireHero* Hero);

    // ---- presentation (clients / listen server) ----
    /** Race palette + rank colours on the monster's body (Tripo skin MIDs, or the mannequin tint). */
    CIRESTEAMSURVIVAL_API bool ApplySkin(ACireMonster* Monster);
    /** True when the race skin material is on the body (it then carries the rank rim itself). */
    CIRESTEAMSURVIVAL_API bool HasSkin(const ACireMonster* Monster);
    /** Cast started (seen on a client): plays the ability's audio cue. */
    CIRESTEAMSURVIVAL_API void OnCastPresented(ACireMonster* Monster, FName AbilityId);

#if !UE_BUILD_SHIPPING
    CIRESTEAMSURVIVAL_API bool RunSmoke(ACireGameMode* Mode);
#endif
}
