#pragma once
// new-champions: gameplay for the Gunblade, Witch Slayer, Huntress and the two Aetheri champions
// (Docs/NewChampions.md). Every skill's numbers (cost, cooldown, effect, range, radius, duration,
// crowd control) come from the Ability Database (Content/Data/Abilities.json, generated by
// Tools/BuildAbilityDB.py); this module holds only the delivery recipe (projectile, cone, ground
// circle, bounce, dash, mark, construct...) and the primary-stat scaling of each skill.
// Everything runs on the server; state reaches clients through replicated buff records,
// constructs, areas, skillshots and combat events.
#include "CoreMinimal.h"

class AActor;
class ACireHero;
class ACireMonster;
class ACireGameMode;
struct FCireHitShape;

namespace CireSignatureSkills
{
    /** Any skill (active, passive, ultimate) owned by this module. */
    CIRESTEAMSURVIVAL_API bool Knows(const FString& Id);
    /** Castable actives and ultimates. */
    CIRESTEAMSURVIVAL_API bool Handles(const FString& Id);
    CIRESTEAMSURVIVAL_API bool IsPassive(const FString& Id);
    CIRESTEAMSURVIVAL_API bool IsUltimate(const FString& Id);
    CIRESTEAMSURVIVAL_API FString Name(const FString& Id);
    CIRESTEAMSURVIVAL_API FString Description(const FString& Id);
    /** Validates slot, resources, cooldown, realm and aim; a failed cast never charges. */
    CIRESTEAMSURVIVAL_API bool Cast(ACireHero* Hero, int32 Slot, const FString& Id);
    /** Targeting / telegraph shape for the ground-aim system and school runes. */
    CIRESTEAMSURVIVAL_API bool DescribeShape(const FString& Id, FCireHitShape& Out);
    /** Skill ids of the new champions (tests, docs). */
    CIRESTEAMSURVIVAL_API const TArray<FString>& AllIds();

    // ---- combat hooks (server) ----
    /** Marks, silver shot, Witchbane, disruption/aegis/nexus fields, banishment immunity. */
    CIRESTEAMSURVIVAL_API float ModifyOutgoingDamage(AActor* Source, AActor* Target, float Amount, const FString& AbilityName);
    /** Slows, marks and purges authored as Ability DB effects of the new skills; basic-attack riders. */
    CIRESTEAMSURVIVAL_API void OnAbilityHit(AActor* Source, AActor* Target, const FString& AbilityName, float Applied);
    /** Hex-mark bounty and Price on Every Soul gold. */
    CIRESTEAMSURVIVAL_API void OnMonsterKilled(ACireMonster* Monster, ACireHero* Killer);
    /** Moonlit Sprint, haste fields. */
    CIRESTEAMSURVIVAL_API float MoveSpeedMultiplier(const ACireHero* Hero);
    /** Haste fields (added to the attack-speed sum). */
    CIRESTEAMSURVIVAL_API float AttackSpeedBonus(const ACireHero* Hero);
    /** scaling-kits: strips a unit's positive buffs (level-15 purge). Returns records removed. */
    CIRESTEAMSURVIVAL_API int32 PurgeBuffs(AActor* Target);
    /** Gunblade: true when the basic attack is a falchion slash (target within close range). */
    CIRESTEAMSURVIVAL_API bool IsCloseQuarters(const ACireHero* Hero, const AActor* Target);
    /** Basic attack release: the style's damage (falchion, Hunter's Stride) and its combat name. */
    CIRESTEAMSURVIVAL_API float ModifyBasicAttack(ACireHero* Hero, AActor* Target, float Damage, bool& bInOutRanged, FString& OutName);
    /** A ranged basic attack landed (Moon Glaive bounces). */
    CIRESTEAMSURVIVAL_API void OnBasicProjectileHit(ACireHero* Hero, AActor* Victim, float Damage, bool bHit);
    /** The gunblade close-quarters switch distance (cm). */
    constexpr float GunbladeMeleeRange = 320.f;
    /** Buff record ids applied by these skills (BuffVisuals.json rows exist for each). */
    CIRESTEAMSURVIVAL_API const TArray<FName>& BuffIds();
#if !UE_BUILD_SHIPPING
    CIRESTEAMSURVIVAL_API bool RunSmoke(ACireGameMode* Mode);
#endif
}
