"""items-v2: print the item catalogue tables for Docs/Items.md from Content/Data/Items.json.

Totals include the recipe parts (the same maths as Cires::Items::Catalog::Finalize).
Usage: python Tools/ItemCatalogDoc.py > catalogue.md   (paste between the CATALOGUE markers)
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA = json.loads((ROOT / "Content/Data/Items.json").read_text(encoding="utf-8"))
ITEMS = {i["id"]: i for i in DATA["items"]}
LABEL = {"primaryStat": "Primary", "health": "HP", "mana": "Mana", "armor": "Armor", "ward": "Ward", "attackSpeed": "AS %",
         "cooldownReduction": "CDR %", "moveSpeed": "MS %", "healthRegen": "HP/s", "manaRegen": "Mana/s", "energyRegen": "Energy/s",
         "damageReduction": "DR %", "damageBlock": "Block", "critChance": "Crit %", "lifesteal": "Lifesteal %"}


def total(iid, seen=()):
    item = ITEMS[iid]
    return item["cost"] + sum(total(c, seen + (iid,)) for c in item.get("components", []))


def stats(item):
    return ", ".join(f"+{v:g} {LABEL.get(k, k)}" for k, v in item.get("stats", {}).items()) or "-"


def special(item):
    parts = [f"**{p['name']}:** {p['text']}" for p in item.get("passives", [])]
    if "use" in item:
        use = item["use"]
        parts.append(f"**{'Use' if item.get('belt') or item.get('instant') else 'Active'}{' - ' + use['name'] if use.get('name') else ''}:** {use['text']}")
    return " ".join(parts) or "-"


def section(title, predicate):
    rows = [i for i in DATA["items"] if predicate(i)]
    print(f"\n### {title} ({len(rows)})\n")
    print("| Item (`id`) | Total (recipe) | Build path | Stats | One-line effect | Passive / active |")
    print("|---|---|---|---|---|---|")
    for i in rows:
        tag = " *(path unique)*" if i.get("uniqueGroup") == "path" else " *(boots)*" if i.get("uniqueGroup") == "boots" else " *(unique)*" if i.get("unique") else ""
        path = " + ".join(ITEMS[c]["name"] for c in i.get("components", [])) or "-"
        print(f"| {i['name']} (`{i['id']}`){tag} | {total(i['id'])}g ({i['cost']}g) | {path} | {stats(i)} | {i.get('effect', '')} | {special(i)} |")


def main():
    print(f"<!-- generated by Tools/ItemCatalogDoc.py: {len(ITEMS)} items -->")
    section("Consumables and tomes", lambda i: i["tier"] == "consumable")
    section("Basic components", lambda i: i["tier"] == "basic")
    section("Epic components", lambda i: i["tier"] == "epic")
    section("Path-defining uniques (one per champion)", lambda i: i.get("uniqueGroup") == "path")
    section("Boots (one pair)", lambda i: i["tier"] == "legendary" and i.get("uniqueGroup") == "boots")
    section("Group on-use actives", lambda i: i.get("use", {}).get("kind") in ("partyBarrier", "partyBuff", "healTarget", "healAllies"))
    section("Other legendaries", lambda i: i["tier"] == "legendary" and not i.get("uniqueGroup")
            and i.get("use", {}).get("kind") not in ("partyBarrier", "partyBuff", "healTarget", "healAllies"))
    print("\n### Recommended builds (Items.json -> recommended; core = the six-slot finished build)\n")
    print("| Role | Starting | Core (in order) | Situational |")
    print("|---|---|---|---|")
    for role, lists in DATA["recommended"].items():
        names = lambda ids: ", ".join(ITEMS[i]["name"] for i in ids)
        print(f"| {role} | {names(lists['starting'])} | {names(lists['core'])} | {names(lists['situational'])} |")


if __name__ == "__main__":
    main()
