@echo off
echo Cire's Team Survival - official Microsoft C++ build tools setup
echo Windows will ask you to approve administrator access.
echo Installation may take several minutes. This does not restart the PC.
powershell.exe -NoProfile -Command "$ErrorActionPreference='Stop'; try { $staging=Join-Path $env:TEMP 'CiresTeamSurvival-BuildTools'; $installer=Join-Path $staging 'vs_BuildTools-17.14.41.exe'; $expected='37BB0FB429D163ECEBD272A865D11A37B906D152BEF960DA2DDB29C2E2FD6EEB'; if (-not (Test-Path -LiteralPath $installer)) { throw 'Prepared Microsoft installer is missing. Ask Codex to prepare it again.' }; $signature=Get-AuthenticodeSignature -LiteralPath $installer; if ((Get-FileHash -LiteralPath $installer -Algorithm SHA256).Hash -ne $expected -or $signature.Status -ne 'Valid' -or $signature.SignerCertificate.Subject -notmatch 'O=Microsoft Corporation') { throw 'Microsoft installer verification failed.' }; $arguments='--quiet --wait --norestart --nocache --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.14.44.17.14.x86.x64 --add Microsoft.VisualStudio.Component.Windows11SDK.22621 --add Microsoft.Net.Component.4.8.SDK --add Microsoft.Net.Component.4.8.TargetingPack'; $installPath='C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools'; if (Test-Path -LiteralPath (Join-Path $installPath 'Common7\Tools\LaunchDevCmd.bat')) { $arguments='modify --installPath '+[char]34+$installPath+[char]34+' '+$arguments }; $process=Start-Process -FilePath $installer -ArgumentList $arguments -Verb RunAs -WindowStyle Hidden -Wait -PassThru; $result=[ordered]@{timestamp=(Get-Date).ToString('o');state='installer-returned';installer=$installer;exitCode=$process.ExitCode;restartRequired=($process.ExitCode -eq 3010);components='MSVC14.44,WindowsSDK22621,NetFx4.8SDK,NetFx4.8TargetingPack'}; $result | ConvertTo-Json | Set-Content -LiteralPath (Join-Path $staging 'setup-status.json') -Encoding utf8; $result | ConvertTo-Json | Write-Host; if ($process.ExitCode -notin @(0,3010)) { throw ('Installer returned '+$process.ExitCode) }; Write-Host 'Microsoft installation completed. Ask Codex to verify the compiler and build the game.'; exit 0 } catch { Write-Host $_.Exception.Message; exit 1 }"
if errorlevel 1 (
    echo Setup did not finish successfully. Review the status above and the setup-status.json file.
) else (
    echo Setup command completed. Ask Codex to verify the compiler and build the game.
)
pause
